### ISSUE TITLE
Chart version naming improvement 

### ISSUE THREAD

**Issue by AshutoshNirkhe** [kuberhealthy/kuberhealthy#1005]
**Describe the solution you would like to see happen**
As of now, we are using chart versions as 69, 70 etc i.e. plain numbers. Can we instead use standard Sem Ver2 naming conventions like v2.7.0 etc ? Any particular reason for not doing like that ?

**How do you propose we build it?**
Include any gory development or architecture details about how you would like to see this get done.

**Additional context**
Nothing major, but just chart naming suggestion.

**Comment by integrii** [comment]
We used to do semver for chart releases long ago, but it turned out not to work so well.  

First, its a little confusing to have semver for your chart and semver again for your app version.  People often also assume that the helm chart version is the version of the app they are installing, even though those are two entirely different versions.

Secondly, doing semver means a human should decide what the next version is.  Right now, our build pipeline for helm and its specs is automated.  Simply upping a release version is pretty easy to automate.

We might do this in the future, but for now I think it's best left automated and "simple" as a single integer.

I appreciate your attention to the project though and welcome this kind of feedback. Thanks for all your participation in kuberhealthy!
