### ISSUE TITLE
Developing statefulset checker 

### ISSUE THREAD

**Issue by Hungrylion2019** [kuberhealthy/kuberhealthy#1038]
**Describe the feature you would like and why you want it**
Just as the title show , why don't we develop the statefulset checker.
 I think kuberhealthy should provide the necessary statefulset resource  for user to use to check thier business.
@integrii

**Comment by integrii** [comment]
I'm not opposed to this. It sounds like a useful check!  You could develop this as your own repo and image, or you could suggest a pull request to this repository.

We never made a stateful set check because we had checks for persistent volumes as well as deployment checks.  However, it makes sense to directly check the stateful set check on it's own as well.

**Comment by Hungrylion2019** [comment]
ok , I had completed the code in our cluster and let it ran . I will spend some time to solve it in the future.
