### ISSUE TITLE
Refactor KIAM check to use a more solid test -- move away from Lambdas

### ISSUE THREAD

**Issue by jonnydawg** [kuberhealthy/kuberhealthy#244]
**Describe the feature you would like and why you want it**
The current KIAM check lists Lambdas as a way to test KIAM metadata intercept services. It could be better to test this differently as Lambas do not really represent KIAM functionality.

**Comment by integrii** [comment]
@jonnydawg wasn't this fixed?  If so, close this one.

**Comment by jonnydawg** [comment]
No, this still utilizes Lambdas

**Comment by jonnydawg** [comment]
Should this be querying and checking the metadata service instead? `"http://169.254.169.254"`

**Comment by integrii** [comment]
That could be a viable way to test KIAM functionality... Perhaps just do an `http.Get` on that URL and check for a token to exist?

However, if KIAM is completely offline, and not restricting calls, then this will appear to pass because a token was found... We need some distinct way to know that KIAM intercepted the request and it worked.  Perhaps we can ask for some way to identify KIAM interception on the [kiam probject](https://github.com/uswitch/kiam)?
