### ISSUE TITLE
REQ: Helm Chart Changelog

### ISSUE THREAD

**Issue by TJM** [kuberhealthy/kuberhealthy#735]
**Describe the feature you would like and why you want it**
We were running v2.2.0 of the kuberhealthy helm chart, now I see that there are new versions... 28.0.0, 32.0.0 and 33.0.0 ... I am not quite sure why it went from 2.2.0 to 28.0.0, seems like we missed a few versions? Either way, it would be nice to have a CHANGELOG for the helm chart so that when we upgrade these seemingly "major" version upgrades, we can see what the breaking changes are.

**Additional context**
Example I find useful: https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/CHANGELOG.md

**Comment by integrii** [comment]
Yeah, that was a big helm chart bump.  We recently deployed a new github action that automatically publishes a new revision of the helm chart whenever the specs for it are merged into master.  That same job also updates our static flat files that people without Helm can use.

Due to the Helm chart changing many times without the actual code changing, it was not possible to keep these versions lined up.

I don't see us likely to make a helm chart changelog due to the administration overhead, but we always do release notes with new launches of Kuberhealthy.  You can see them in the [releases](https://github.com/Comcast/kuberhealthy/releases) section on github.

We will be very conscious of breaking existing users of the helm chart.  I think this should be avoidable in nearly all cases.

**Comment by TJM** [comment]
Having the helm chart version match the app version *rarely* works because helm chart versions do not support the "x.y.z-R" type releases like RPMs... so many apps have diverged that it is no longer expected, but I am not sure I expected it to go quite so high. :)

I would have thought that the gh-action that is generating the helm stuff could have auto-generated the changelog, but I understand. If I can figure out how to automate it, I will PR it back in.

**Comment by integrii** [comment]
Because each new version is essentially one change (the automation fires on every merge to master), we would always have a very small changelog.  We also aren't making tags when we do a helm release (we only do those on app releases).

**Comment by TJM** [comment]
Hmm, there is usually some "job" (gh-action, gitlab-ci, etc) that combines all the commit messages to a CHANGELOG.md during a release, but those are usually less useful than when someone "edits" the CHANGELOG.md directly, at least for "major/breaking" changes. Running two different release processes from the same repo might prove interesting. Many places (jfrog, bitnami, etc) run all their charts in one repo (which seems wrong to me too, cause you can't tag a release that way), so it must be possible to manage at a sub-dir level?
