### ISSUE TITLE
Add support for exposing custom metrics generated by checks

### ISSUE THREAD

**Issue by adriananeci** [kuberhealthy/kuberhealthy#750]
**Describe the feature you would like and why you want it**
Currently kuberhealthy exposes only `kuberhealthy_check` and `kuberhealthy_check_duration_seconds` metrics per configured khcheck.

There are some cases where only these 2 metrics are not enough when defining KPIs or SLTs.
One such example could be an ingress or an egress check. It is not enough to have only the Fail/Success state and the duration of the check. You also need a metric like http call duration or if you have multiple http calls you probably want to count the percentage of the requests that failed/succeeded.  

Some other examples might be to measure the k8s api latency or throughput or deployment scale time.

As a workaround we can push the custom metrics to a pushgateway instance, but the drawback here is that we cannot leverage metrics of type counter and also is a bit complicated to decide between a fresh value or a value from a previous run(see this [robustperception blog](https://www.robustperception.io/aggregating-across-batch-job-runs-with-push_time_seconds)). Another drawback is the fact that we have to keep in sync kuberhealthy metrics with custom metrics generated by the `khchecks`.

**Additional context**
One way to accomplish this freedom of exposing  custom metrics could be by extending the https://github.com/Comcast/kuberhealthy/blob/e712c07cee05d2d9f9f20352a5991a81fbcec636/pkg/health/state.go#L23 state of the check and adjust metrics generation method https://github.com/Comcast/kuberhealthy/blob/e712c07cee05d2d9f9f20352a5991a81fbcec636/pkg/metrics/exporter.go#L26 
accordingly.

Then it will be the responsibility of the check itself to expose or not custom metrics. These metrics can be sent together with the report status
https://github.com/Comcast/kuberhealthy/blob/e712c07cee05d2d9f9f20352a5991a81fbcec636/pkg/checks/external/status/main.go#L7

**Comment by adriananeci** [comment]
I can give it a try if there are no other concerns regarding this approach.

**Comment by integrii** [comment]
Thanks for the carefully thought through proposal here.  My initial impression is that this would be complicated due to Kuberhealthy not having a database of any kind.  The metrics would have to either be stored in the `khstate` objects, or kept in memory, which would be wiped on any pod restart event.

We actually use pushgateway internally ourselves for metrics that don't come with Kuberhealthy out of the box... 

I am leaving this one open for more thought/consideration from others, but I am leaning toward this not being on the critical path of what the project looks to accomplish.
