### ISSUE TITLE
Additional filters to json status page

### ISSUE THREAD

**Issue by isaaguilar** [kuberhealthy/kuberhealthy#826]
**Describe the feature you would like and why you want it**
It'd be nice to have additional filter to the status page for "name" of the check. So `?namespace=default&name=mycheck` returns only the single check:

```
{
  "OK": true,
  "Errors": [],
  ...
  "CheckDetails": {
    "default/mycheck": {
      "OK": true,
      "Errors": [],
      ...
    }
  }
}
```

and/or a query like `?name=mycheck` could return the range of checks matching that name in all the namespaces.

```
{
  "OK": true,
  "Errors": [],
  ...
  "CheckDetails": {
    "default/mycheck": {
      "OK": true,
      "Errors": [],
      ...
    },
    "myns/mycheck": {
      "OK": true,
      "Errors": [],
      ...
    },
  }
}
```

**Comment by integrii** [comment]
This seems like a helpful idea, but we have some thinking to do about how this behaves when `khjob` states are returned.  

Also, if we are only going to return one item from `CheckDetails`, we might as well change the returned JSON to only show the details from one check.  However, if we are doing that we would probably want to create a different endpoint so that we don't change the returned json structure depending on the parameters that are passed in.
