### ISSUE TITLE
Kuberhealthy gets stuck parsing non-existent runDuration for prometheus metrics

### ISSUE THREAD

**Issue by joshulyne** [kuberhealthy/kuberhealthy#893]
**Describe the bug**
Kuberhealthy gets stuck and fails to provision any checks when parsing non existent runDuration -- or runDuration for a khchecker pod that has never been able to come up.

When khcheck pod hasn't been created, it gets this error: `Check execution error: no containers found in checks PodSpec` and kuberhealthy updates the khstate with this error. However, the prometheus metrics exporter tries to parse the runDuration that has never been set since the khcheck pod never ran and gets stuck with this error -- failing to provision any more khcheck runs:
```
time="2021-04-15T00:06:48Z" level=error msg="Error parsing run duration:  for metric: kuberhealthy_check{check=\"kuberhealthy/dns-status-external\",namespace=\"kuberhealthy\",status=\"0\",error=\"Check execution error: no containers found in checks PodSpec|\"} error: time: invalid duration \"\""
```

**Comment by tomer1983** [comment]
We are dealing with the same issue on ocp3.11

**Comment by JoseAlvarezSonos** [comment]
Anyone found a solution to this? We are also seeing the same issue with v2.7.1, but strangely it's only happening in 1 of our clusters, the other clusters work fine, the only difference is that the name of checks is significantly higher than in the other clusters, any ideas?

**Comment by orondon** [comment]
is there any update to this issue? 
I'm running on OCP 4.6 and trying to do a network connection khcheck

a deployment khchecks work well, but with this network connection check 

`apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  labels:
    app.kubernetes.io/instance: kuberhealthy
  name: network-connection-artifactory
  namespace: kuberhealthy
spec:
  podSpec:
    containers:
      - env:
          - name: CONNECTION_TARGET
            value: 'tcp://artifactory.mydomain.ca:443'
          - name: HTTPS_PROXY
            value: 'http://proxy.mydomain.ca:8888/'
          - name: HTTP_PROXY
            value: 'http://proxy.mydomain.ca:8888/'
        image: 'kuberhealthy/network-connection-check:v0.2.0'
        imagePullPolicy: IfNotPresent
        name: artifactory
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    securityContext:
      fsGroup: 999
      runAsUser: 999
  runInterval: 2m
  timeout: 1m`


the checker pods cannot report status
`time="2022-11-12T00:44:31Z" level=info msg="Found instance namespace: kuberhealthy"
time="2022-11-12T00:44:31Z" level=info msg="Kuberhealthy is located in the kuberhealthy namespace."
time="2022-11-12T00:44:31Z" level=info msg="Check time limit set to: 48.184062995s"
time="2022-11-12T00:44:31Z" level=info msg="CONNECTION_TARGET_UNREACHABLE could not be parsed."
time="2022-11-12T00:44:31Z" level=info msg="Running network connection checker"
time="2022-11-12T00:44:31Z" level=error msg="Network connection check determined that tcp://artifactory.mydomain.ca:443 is DOWN: dial tcp: lookup artifactory.mydomain.ca on 1.4.0.10:53: no such host"
time="2022-11-12T00:45:09Z" level=info msg="Error reporting failure to Kuberhealthy servers: bad POST request to kuberhealthy status reporting url: Post http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus: http: ContentLength=179 with Body length 0"
time="2022-11-12T00:45:09Z" level=error msg="Error running network connection check for: tcp://artifactory.mydomain.ca:443"
time="2022-11-12T00:45:09Z" level=info msg="Done running network connection check for: tcp://artifactory.mydomain.ca:443"`

and the kuberhealthy pod 

`time="2022-11-12T00:42:04Z" level=info msg="Found instance namespace: kuberhealthy"
time="2022-11-12T00:42:04Z" level=info msg="Kuberhealthy is located in the kuberhealthy namespace."
time="2022-11-12T00:42:04Z" level=info msg="KH_EXTERNAL_REPORTING_URL environment variable not set, using default value"
time="2022-11-12T00:42:04Z" level=info msg="External check reporting URL set to: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus"
I1112 00:42:25.325797       1 request.go:668] Waited for 1.193312597s due to client-side throttling, not priority and fairness, request: PUT:https://1.4.0.1:443/apis/comcast.github.io/v1/namespaces/kuberhealthy/khstates/network-connection-artifactory
time="2022-11-12T00:43:28Z" level=error msg="Error running check: network-connection-artifactory in namespace kuberhealthy: kuberhealthy/network-connection-artifactory: timed out waiting for checker pod to report in"
time="2022-11-12T00:43:33Z" level=error msg="Error parsing run duration:  for metric: kuberhealthy_check{check=\"kuberhealthy/network-connection-artifactory\",namespace=\"kuberhealthy\",status=\"0\",error=\"Check execution error: kuberhealthy/network-connection-artifactory: timed out waiting for checker pod to report in\"} error: time: invalid duration \"\""
time="2022-11-12T00:43:38Z" level=error msg="Error parsing run duration:  for metric: kuberhealthy_check{check=\"kuberhealthy/network-connection-artifactory\",namespace=\"kuberhealthy\",status=\"0\",error=\"Check execution error: kuberhealthy/network-connection-artifactory: timed out waiting for checker pod to report in\"} error: time: invalid duration \"\""
time="2022-11-12T00:43:48Z" level=error msg="Error parsing run duration:  for metric: kuberhealthy_check{check=\"kuberhealthy/network-connection-artifactory\",namespace=\"kuberhealthy\",status=\"0\",error=\"Check execution error: kuberhealthy/network-connection-artifactory: timed out waiting for checker pod to report in\"} error: time: invalid duration \"\""
`
some other issue reported that this could happen on the first check due to race condition, but subsequent checks keep failing
`time="2022-11-12T00:55:25Z" level=error msg="Error running check: network-connection-artifactory in namespace kuberhealthy: kuberhealthy/network-connection-artifactory: timed out waiting for checker pod to report in"
time="2022-11-12T00:55:33Z" level=error msg="Error parsing run duration:  for metric: kuberhealthy_check{check=\"kuberhealthy/network-connection-artifactory\",namespace=\"kuberhealthy\",status=\"0\",error=\"Check execution error: kuberhealthy/network-connection-artifactory: timed out waiting for checker pod to report in\"} error: time: invalid duration \"\""
time="2022-11-12T00:55:38Z" level=error msg="Error parsing run duration:  for metric: kuberhealthy_check{check=\"kuberhealthy/network-connection-artifactory\",namespace=\"kuberhealthy\",status=\"0\",error=\"Check execution error: kuberhealthy/network-connection-artifactory: timed out waiting for checker pod to report in\"} error: time: invalid duration \"\""`

**Comment by gil-brown-argus** [comment]
does any one was able to resolve this issue?

**Comment by jnonino** [comment]
Hi everyone, I had the same error message with a custom check I was creating and the problem was the check timeout. I increased the timeout and the check ended successfully.

Maybe what you've been experiencing is a different scenario but wanted to leave a comment in case you find it useful!
