### ISSUE TITLE
what is the code version corresponding to the image kuberhealthy/kuberhealthy:latest?

### ISSUE THREAD

**Issue by harryyann** [kuberhealthy/kuberhealthy#947]

**Comment by jonnydawg** [comment]
Latest will typically represent to our current master branch -- however, we just recently changed our github build actions to use the tag `unstable` instead of `latest`. If you're curious in what version release the current latest image is, it would be `v2.4.1-rc` (release candidate due to updates with the check client). Otherwise, latest will match the latest release version.
