### ISSUE TITLE
go mod dependencies in v.2.4.1 when writing a custom check

### ISSUE THREAD

**Issue by claudenm** [kuberhealthy/kuberhealthy#954]
Our team is planning on using kuberhealthy to write some checks.  I cloned the main branch of the project and copied the [deployment check](https://github.com/kuberhealthy/kuberhealthy/tree/master/cmd/deployment-check) to a new directory to start tweaking it.  When I initialized a new go module, and ran `go mod tidy` I got this error:

```
go: foo imports
        github.com/kuberhealthy/kuberhealthy/v2/pkg/checks/external/checkclient: github.com/kuberhealthy/kuberhealthy/v2@v2.4.1: parsing go.mod:
        module declares its path as: github.com/Comcast/kuberhealthy/v2
                but was required as: github.com/kuberhealthy/kuberhealthy/v2
```

I noticed this change: https://github.com/kuberhealthy/kuberhealthy/blame/master/go.mod#L1 recently but no corresponding release.  Are we expected to use the rewrite directive in `go.mod` or is a patch pending?

Here's a simple file that demonstrates the issue:

`main.go`
```go
package main

import (
	"os"

	"github.com/kuberhealthy/kuberhealthy/v2/pkg/checks/external/checkclient"
)

func main() {
	_ = checkclient.ReportSuccess()
	os.Exit(0)
}
```

run `go mod init foo && go mod tidy` and the error message above will be displayed.

**Comment by jonnydawg** [comment]
Hey, thanks for making an issue for this!

I have noticed this issue to ever since our organization migration and is currently scheduled for fix with our next release.

The current solution that I have *for now* is to have the version pinned to a commit hash instead of a semver release version. Include the following requirement your project's `go.mod` file:

```code
require (
	github.com/kuberhealthy/kuberhealthy/v2 v2.4.2-0.20210521171722-f885b230396a
)
```

Run a `go mod tidy` and you should be good to go!

You may run into an error that also requires you to have `github.com/sirupsen/logrus` as well -- in that case `go get github.com/sirupsen/logrus` should do the trick.

@claudenm

**Comment by claudenm** [comment]
Thanks @jonnydawg, I'll close this out.  I appreciate the guidance!
