### ISSUE TITLE
When a khcheck is caught changed, rerun only that specific khcheck rather than rerun all khchecks.

### ISSUE THREAD

**Issue by harryyann** [kuberhealthy/kuberhealthy#999]
**Describe the feature you would like and why you want it**

When I changed one khcheck in my cluster, all khcheck will be rerun. But I want  one khcheck only run at the time I want it to run. I don't want any khcheck changes to interfere with the scheduled running time of other khchecks. 

For example, I want my daemonset khcheck only run at 1:00 am everyday. So I set the runInterval is 24h and trigger it to run at 1:00 am. But if I changed the other khchecks at other times or add other khcheck, the daemonset khcheck will rerun instantly and it will not run at 1:00 am.

Is there any method to avoid this thing happen? Could kuberhealthy considered  to add cronJob to do check, or each khcheck modification can only restart this khcheck and do not effect others?

**Comment by integrii** [comment]
I think this is do-able.  Right now, Kuberhealthy does a reload on all checks every time anything changes to ensure that all state is correct and to keep the code simple.  This was the first implementation of our check reconfiguration.

I don't see (right now) any reason why we couldn't reload an individual check...  Kuberhealthy knows all checks that it currently manages from a map it maintains [here](https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/kuberhealthy/kuberhealthy.go#L39).  Then, [here](https://github.com/kuberhealthy/kuberhealthy/blob/ae29563cbbc17bb6b412cf9d57b52f5b42bd2c6e/cmd/kuberhealthy/kuberhealthy.go#L1719) in the code, checks are watched for changes.  We could augment [this code](https://github.com/kuberhealthy/kuberhealthy/blob/ae29563cbbc17bb6b412cf9d57b52f5b42bd2c6e/cmd/kuberhealthy/kuberhealthy.go#L461) to return which check changed, then modify [this code](https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/kuberhealthy/kuberhealthy.go#L227) to only reload that specific check instead of all of them.
